### ISSUE TITLE
semanticaing servants

### ISSUE THREAD

**Issue by thewchan** [EmmaSweeney/william-shakespeare_timon-of-athens#2]
This might be intentional and acceptable; but in act-1 line 393:

```
<i epub:type="z3998:stage-direction">Trumpets sound. Enter <b epub:type="z3998:persona">Lord Timon</b>, addressing himself courteously to every suitor; a <b epub:type="z3998:persona">Messenger</b> from <b epub:type="z3998:persona">Ventidius</b> talking with him; <b epub:type="z3998:persona">Lucilius</b> and other <b epub:type="z3998:persona">Servants</b> following.</i>
```

"Servants" is not capitalized nor treated as a persona in the scan:
![image](https://user-images.githubusercontent.com/49702524/155804348-f280cc4d-3520-4eb9-b409-8cddff9ca172.png)
![image](https://user-images.githubusercontent.com/49702524/155804389-09fb67bf-0fce-4915-b94b-396c94702931.png)

**Comment by EmmaSweeney** [comment]
This was intentional. "Servants" is treated as a persona throughout the play because the servants have dialogue.
